/** @file compat.h
 *  Types and macros for compatibility with other headers.
 */

/*
 * Copyright (C) 2006 Philip Lewis <pcl@pclewis.com>
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef _MEMDIR_COMPAT_H_
#define _MEMDIR_COMPAT_H_

/* BSD types used by libevent (not POSIX/ANSI) */
typedef unsigned       char u_char;
typedef unsigned       int  u_int;
typedef unsigned short int  u_short;
typedef unsigned long  int  u_long;

/* win32 crap {{{ */
#ifdef WIN32

#pragma warning(disable : 4127) /* VC6: conditional expression is constant */
#pragma warning(disable : 4201) /* VC6: nonstandard nameless struct */
#pragma warning(disable : 4201) /* VC6: nonstandard nameless struct */
#pragma warning(disable : 4505) /* VC6: unreferenced function removed */
#pragma warning(disable : 4244) /* VC6: possible loss of data */
#pragma warning(disable : 4201)

/* need winsock for some stuff */
#pragma comment(lib, "wsock32.lib")

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#undef WIN32_LEAN_AND_MEAN

typedef SSIZE_T ssize_t;
#define F_OK 0
#define X_OK 1
#define W_OK 2
#define R_OK 4
#define S_IRWXU 0700
#define S_IRUSR 0400
#define S_IWUSR 0200
#define S_IXUSR 0100

typedef unsigned __int64 u_int64_t;
typedef unsigned __int32 u_int32_t;
typedef unsigned __int16 u_int16_t;
typedef unsigned __int8  u_int8_t;

#endif /* }}} WIN32 */

#endif /* !_MEMDIR_COMPAT_H_ */
